# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
    config.vm.box_check_update = false

    # Give VM 1/4 system memory & access to half of cpu cores on the host
    cpus = `sysctl -n hw.physicalcpu`.to_i
    cpus = [8, cpus / 2].min if cpus > 1
    mem  = 1365
    mem  = mem / 4 if mem > 2048

    config.vm.define "macos" do |cfg|
        cfg.vm.provider "virtualbox" do |v|
            v.cpus   = cpus
            v.memory = mem
        end
        cfg.vm.box         = "mcandre/vagrant-macos-homebrew"
        cfg.vm.box_version = "0.0.1"
        cfg.vm.synced_folder ".", "/vagrant", disabled: true
        cfg.vm.provision     "shell", inline: %{
su vagrant -c 'brew update'
su vagrant -c 'brew install rsync conan python3'
su vagrant -c 'pip3 install pyyaml'
ln -s /usr/local/bin/python3 /usr/local/bin/python
su vagrant -c 'echo "source /etc/profile">~/.bashrc'
su vagrant -c 'echo "export MACOSX_DEPLOYMENT_TARGET=10.7">>~/.bashrc'
gem install fpm --no-ri --no-rdoc
}
    end

    config.vm.define "windows" do |cfg|
        cfg.vm.provider "virtualbox" do |v|
            v.cpus   = cpus
            v.memory = mem
        end
        cfg.vm.box            = "mcandre/windows-amd64"
        cfg.vm.box_version    = "0.0.1"
        cfg.vm.communicator   = :winssh
        cfg.winssh.insert_key = false

        cfg.vm.synced_folder ".", "/cygdrive/c/vagrant", disabled: true
        cfg.vm.provision     "shell", upload_path: "C:\\Windows\\Temp\\bootstrap.bat", inline: %{
choco uninstall -y rsync
cd "C:/Program Files/Git"
curl -fsSL https://mirrors.huaweicloud.com/repository/msys2/msys/x86_64/rsync-3.1.3-1-x86_64.pkg.tar.xz | tar xJ
curl -L https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe -o vs_buildtools_full.exe
start vs_buildtools_full.exe --wait --quiet --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows81SDK --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.Component.VC.Runtime.UCRTSDK 
curl -L https://disq.us/url?url=https://download.microsoft.com/download/5/F/7/5F7ACAEB-8363-451F-9425-68A90F98B238/visualcppbuildtools_full.exe:0BjsZPTJcz6FCYlIl89HGYq2YGk -o vs_buildtools.exe
start vs_buildtools.exe --wait --quiet --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows81SDK --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.Component.VC.Runtime.UCRTSDK
choco install -yr --no-progress python2 nsis
choco install -yr --no-progress cmake --installargs 'ADD_CMAKE_TO_PATH=System'
C:/Python27/Scripts/pip install -q conan
powershell Restart-Service sshd
%}
    end

end
